purecloud_auth:
  purecloud_client_id:
      default: ''
  purecloud_client_secret:
      default: ''
  purecloud_apse_client_id:
      default: ''
  purecloud_apse_client_secret:
      default: ''
  purecloud_apne_client_id:
      default: ''
  purecloud_apne_client_secret:
      default: ''
  purecloud_euw_client_id:
      default: ''
  purecloud_euw_client_secret:
      default: ''
  purecloud_euc1_client_id:
      default: ''
  purecloud_euc1_client_secret:
      default: ''
 
